### ISSUE TITLE
Unicode option in hyperref

### ISSUE THREAD

**Issue by goblou** [latex3/hyperref#137]
I'm unable to find guidance on the following.  What precisely occurs upon electing the hyperrerf option "Unicode encoded pdf strings, by default true with XeTEX and LuTEX" (manual, p. 13)?  Is this a reference to something other than the encoding of the document as a whole, as to which I have in TeXShop a preamble opening as follows:

%%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode  

Is this option superfluous by virtue of the above code?  Why does it not reference XeLaTeX?

**Comment by muzimuzhi** [comment]
> Is this option superfluous by virtue of the above code? Why does it not reference XeLaTeX?

No, and it is the underlying engines (e.g., xetex, luatex) that are related. Since xelatex is a combination of engine (xetex) and format (latex2e), xelatex is covered when it says "xetex (engine)".

- The magic comment you have in TeXShop is used to help editors to decode tex files.
 - hyperref's option `unicode` is used to keep the pdf string (for example, the bookmark title and pdf title) in unicode encoding. This is especially helpful if the encoding of tex file is not compatible with unicode. For example, Chinese users may use GBK encoding to store their tex files.

**Comment by davidcarlisle** [comment]
Thanks @muzimuzhi  for answering, as this was a a support question not a bug report I'll close with no action.

**Comment by goblou** [comment]
Thank you, @muzimuzhi, for explaining this.
