### ISSUE TITLE
Bug in xr-hyper.sty 

### ISSUE THREAD

**Issue by aisejohan** [latex3/hyperref#143]
Using the command `hyperref[label]{text}` to refer to a label in an external file no longer works. When I use the file `xr-hyper.sty` from 7f30954 then it does work. The smallest example I could think of you can find below (sorry for clumsy latex). It would be great if this could be fixed.

Put the next part in a file a.tex

`\documentclass{amsart}
\usepackage{xr-hyper}
\usepackage{hyperref}
\externaldocument[b]{b}
\begin{document}
\phantomsection
\label{aa}
Hello!
\hyperref[bbb]{BB}
\end{document}`

Put the next part in a file b.tex

`\documentclass{amsart}
\usepackage{xr-hyper}
\usepackage{hyperref}
\externaldocument[a]{a}
\begin{document}
\phantomsection
\label{bb}
Hello!
\hyperref[aaa]{AA}
\end{document}`

**Comment by davidcarlisle** [comment]
Thanks for the clear test file  it is generating a %-encoded URL

`b.pdf{}{}#section*.1{}{}`

with spurious `{}{}`  I can confirm it worked in tl2018, we should be able to fix that again sorry for the inconvenience.

**Comment by u-fischer** [comment]
Could you check with the version in https://github.com/latex3/hyperref/pull/140 ?

**Comment by davidcarlisle** [comment]
@aisejohan  actually I think we (or at least @u-fischer :-) has fixed this already, could you test your real document against the version here

https://github.com/latex3/hyperref/pull/140

There are in fact two unmerged pull requests currently

https://github.com/latex3/hyperref/pulls

Been a bit distracted lately...

If your real documents are fixed with these we should push out an update.

**Comment by aisejohan** [comment]
Yes, this works for https://github.com/stacks/stacks-project Thanks for all your work on hyperref!

**Comment by u-fischer** [comment]
The fix has been uploaded to ctan.
