### ISSUE TITLE
Suppress hyperref unicode warning

### ISSUE THREAD

**Issue by cykerway** [latex3/hyperref#150]
Code:

```
\documentclass[pdftitle=abc]{article}
\usepackage[unicode]{hyperref}
\begin{document}
abc
\end{document}
```

Log:

```
Package hyperref Warning: XeTeX driver only supports unicode.
(hyperref)                Enabling option `unicode'.
```

I'm not sure why hyperref warns me when I have passed unicode option. I know it's pdftitle creating the warning and it can be suppressed by a unicode option before pdftitle in the global option list. But I really hate local options not taking precedence over global ones. I'd like to understand what's happening here and if it's a bug. I'm compiling the file with xelatex.

I think it'd be better if global options are merged with local options then the merged options are processed.

**Comment by u-fischer** [comment]
It is not really a bug, but history: The default value of `unicode` was at the start false, but with `xelatex`  `hyperref` had to force the value to true and so added a warning when it switches it (which happens when it encounters your `pdftitle`). 

The `unicode` option is unneeded with xelatex (and lualatex), but currently the only way to avoid the warning is to explicitly use `unicode` *before* all keys which sets text. 

We will change the behaviour in the next hyperref version and remove the warning.
