### ISSUE TITLE
\nameref and \index

### ISSUE THREAD

**Issue by hvoss49** [latex3/hyperref#222]
Using an `\index{foo|(}`  in a chapter/section command is not the best style, but possible.
However, using a `\nameref`  referring to a label inside such a chapter/section will execute
the `\index`  command with an entry in the idx file and a makelndes run will use this entry
instead of the following correct one. In the index we get "bar, 3--10" instead of "bar 9,--10".

A modification of `\T@nameref` solves the problem:

```
\documentclass{book}
\usepackage{makeidx}\makeindex
\usepackage{nameref}

\iffalse%        make \iftrue and it works
\makeatletter
\def\T@nameref#1{%
  \begingroup
    \let\label\@gobble
    \let\index\@gobble%%%%%.  NEW %%%%%
    \NR@setref{#1}\@thirdoffive{#1}%
  \endgroup
}% 
\makeatother
\fi
\usepackage{blindtext}
\begin{document}

\tableofcontents
\chapter{Foo}

\nameref{bar}  (\verb/\nameref{bar}/)
is the problem: the current page is used 
for the \verb/\index{bar|(}/ in the following
chapter, which appears 6 pages later.

\blinddocument
\index{demo}

\chapter{\label{bar}Bar\index{bar|(}}%%%% 

\Blindtext
\index{bar|)}

\printindex

\end{document}

```
The wrong `idx` file:

> \indexentry{bar|(}{3}
> \indexentry{demo}{8}
> \indexentry{bar|(}{9}
> \indexentry{bar|)}{10}

Up-to-date TL2021

**Comment by u-fischer** [comment]
One certainly want to suppress a `\label` in a `\nameref` to avoid multiply labels. 

But I'm not convinced that every author/document wants to avoid that a `\nameref` adds something to an index or a glossary. I mean you are typing `Bar` on page 3, so why shouldn't the index have a pointer to page 3? And similar for glossaries or acronyms.

I think you should use the optional argument if you don't want the index in the reference:

~~~~
\chapter[Bar]{\label{bar}Bar\index{bar|(}}
~~~~

**Comment by hvoss49** [comment]
This is not the point: A `\label` is valid code in a sectioning or caption command. But an `\index` not. From my point of view the two commands   should be similiar  handled by  ` \nameref`

**Comment by u-fischer** [comment]
? What do you mean by that \index is not valid? You are using it, aren't you?

**Comment by hvoss49** [comment]
A label in a sectioning command is "gobbled" by  `\nameref` but an `\index` command not.

**Comment by u-fischer** [comment]
I know that. But imho that is by design. Currently you can choose  if \nameref should create an index entry or not. It is up to your code. Why should nameref force it? Do you really think *every* author will want the Foo entry and not the Bar entry here:

~~~~
\documentclass{article}
\usepackage[nonewpage]{imakeidx}
\makeindex
\usepackage{hyperref}


\begin{document}
\section{This is about Bar\index{Bar}}\label{bar}

\section[This is about Foo]{This is about Foo\index{Foo}}\label{foo}

\newpage
\nameref{bar}

\nameref{foo}

\printindex
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/145589494-1c0bedce-278b-4a9f-ae52-42ba500d1733.png)

**Comment by hvoss49** [comment]
THis was not my example. It is this one:

```
\documentclass{article}
\usepackage[nonewpage]{imakeidx}
\makeindex
\usepackage{hyperref}


\begin{document}

\section{Baz}

\nameref{bar}

\newpage


\section{This is about Bar\index{Bar}}\label{bar}

\section[This is about Foo]{This is about Foo\index{Foo}}\label{foo}

\newpage
\nameref{bar}

\nameref{foo}

\printindex
\end{document}

```

<img width="285" alt="Bildschirmfoto 2021-12-10 um 15 47 26" src="https://user-images.githubusercontent.com/12891199/145592615-024db3e8-fc49-4b85-95e9-d2650cabd145.png">

And why should it by design? An `\index` is just like `\label` not in the TOC-File and this is the reason
why it should also be gobbled by `\nameref`

**Comment by u-fischer** [comment]
`\index` is not like `\label`. A `\label{key}` should be issued only once in a document. `\index{name}`  can appear many times. So the decision if and where to suppress `\index` (and commands like \cite, \acro, \gls etc) should be made independantly from the question if and where to suppress `\label`.

The LaTeX kernel has decided that `\index` should be suppressed in the toc and the header, that is imho a sensible design decision, but it doesn't imply that `\index` should also be suppressed in the middle of section 2 only because it is inserted by a `\nameref`. 

Look at your own example: `Bar` is shown on pages 1,2,3 and the index shows `1-3`. `Foo` is on page 2 and 3 but your index shows only 2. Why do you think the second is better? Wouldn't you think as a reader that an index entry got lost?

**Comment by hvoss49** [comment]
Sigh ... It is simply wrong if I have a `\nameref{}`  which executes an `\index{foo|(}` which appears in a section command 100 pages later. Then an "foo, 1--100"  will be in the index, but there is no foo indexed in  the first 99 pages. However, I'll give it up ...

**Comment by u-fischer** [comment]
Yes, I know that it is wrong. But as you said at the start "Using an `\index{foo|(}` in a chapter/section command is not the best style". And I can not break valid uses of \index in a nameref to repair bad style. The title of a section is passed around quite a lot, and imho you shouldn't add fragile (here not technically but conceptually fragile) commands to a moving argument  if you can avoid it.

**Comment by davidcarlisle** [comment]
The fact that an `\index` range start that is inserted by `\nameref` is probably wrong does not mean that `\nameref` should drop index.  A normal (non-range) `\index` entry that is in text re-inserted by `\nameref` is quite natural to generate an index entry. `\nameref` can not parse the internal structure of the index entry and decide whether to drop it or not.
