### ISSUE TITLE
Version v7.00o breaks `\DeclareHookRule`

### ISSUE THREAD

**Issue by dbitouze** [latex3/hyperref#235]
With v7.00n version of `hyperref`, the following MCE:

```latex
\documentclass{article}
\usepackage{sillypage}
\usepackage{hyperref}
\begin{document}
Foo
\end{document}
```
worked nicely but, with v7.00o, the first line of the resulting PDF file is “sillypagehyperrefbegindocument”.

This is clearly related to the following which is at the end of `sillypage.sty`:
```latex
\DeclareHookRule { begindocument }
  { sillypage } { after } { hyperref }
```

**Comment by dbitouze** [comment]
More generally, v7.00n version of `hyperref` breaks `\DeclareHookRule`, at least when its first argument is `begindocument` and its second one is `.` (or equivalent), since the same kind of trouble arises with he packages that contains such declaration: `hypdestopt`, `metastr` and `fnpct`.

**Comment by u-fischer** [comment]
I reported the underlying issue here https://github.com/latex3/latex2e/issues/818. 
Regarding hyperref:  I will update it so that it no longer loads nameref in begin document (which is imho not so great anyway) but when hyperref is loaded.  Until the update is there you can simply load nameref in the preamble.

**Comment by u-fischer** [comment]
nameref is now loaded earlier and the latex issue will be handled there.
