### ISSUE TITLE
ref link no longer works with revtex

### ISSUE THREAD

**Issue by daviehh** [latex3/hyperref#284]
Referencing equations/figures seems broken since the last update. Example:

```tex
\documentclass[aps,pra,twocolumn,superscriptaddress]{revtex4-2}
\usepackage{amsmath}

\usepackage{graphicx}

\usepackage[colorlinks=true,linkcolor=blue,urlcolor=black,citecolor=blue]{hyperref}

\begin{document}

\section{some section}

Here's an equation
\begin{align}
    x \label{eqn}
\end{align}

\begin{figure}
    \centering
    \includegraphics[width=.3\textwidth]{example-image-a}
    \caption{Fig example}\label{fig}
\end{figure}

Testing equation with Eq.~\eqref{eqn}.

Testing figure with Fig.~\ref{fig}.

\end{document}
```

The file compiles with warning `Suppressing link with empty target.` for the `\ref`/`\eqref`, and the resulting text is not linked/clickable. Also reproducible with the documentclass `revtex4-1`. Given `revtex4-1` has not been updated for years, maybe it's due to recent changes in hyperref? The documentclass article does not seem affected. Thanks!

**Comment by u-fischer** [comment]
it is due to change in LaTeX: the kernel now supports five values in `\label` directly, and so hyperref no longer redefines `\label`. But revtex redefines `\label` and so overwrites the kernel definition again. 

I will discuss what to do, for now restore the definition:

~~~~
\let\orilabel\label
\documentclass[aps,pra,twocolumn,superscriptaddress]{revtex4-2}
\let\label\orilabel
~~~~

**Comment by u-fischer** [comment]
The newest hyperref contains a work-around, but revtex should nevertheless correct its code.
