### ISSUE TITLE
Package load order is wrong: load cleveref *after* hyperref.

### ISSUE THREAD

**Issue by deepk96** [latex3/hyperref#347]
Getting this error while generating PDF from Enterprise Architecture.
Installed and uninstalled MikTex multiple times but shows same Error.
[main.log](https://github.com/user-attachments/files/16269576/main.log)
Attached is the log

**Comment by muzimuzhi** [comment]
It's a long existing requirement that `cleveref` has to be loaded after `hyperref`. I doubt the same loading order was working before.

**Comment by deepk96** [comment]
Yes previously it was working but after an update I am getting this issue.

**Comment by u-fischer** [comment]
well as @muzimuzhi wrote, cleveref must be loaded after hyperref, and that is not new. Apart from this, you have a mix of old and new, e.g. your LaTeX format is from 2020-02-02 and you combine that with packages from 2024. Don't do this. Update always everything and not only parts.

**Comment by muzimuzhi** [comment]
BTW the first error in the attached [main.log](https://github.com/user-attachments/files/16269576/main.log)
```
! Package cleveref Error: cleveref must be loaded after hyperref!.
```
was there since `cleveref` v0.21 (2017/07/10), see [this diff from texlive's SVN repo](https://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/cleveref/cleveref.sty?r1=46548&r2=46549&). So it seems you updated from a quite old version of MiKTeX.

I would suggest to just adjust the loading order in your document.

**Comment by deepk96** [comment]
Is the loading order fixed in further versions of MiKTeX ?
How can I change the loading order...Do I need to modify any file or any
other method is there.
?
Please suggest...

**Comment by muzimuzhi** [comment]
It's controlled by your `main.tex`. The position and order of `\usepackage{<pkgname>}` in `main.tex` is the time and order each of such packages is loaded.

(We're off-topic, as this is `hyperref`'s bug tracker.)
