### ISSUE TITLE
Unwanted spaces appearing since the beginning of Nov. 2024

### ISSUE THREAD

**Issue by Uwe-Schmock** [latex3/hyperref#363]
When I typeset the example file below, I get unwanted spaces at the locations where I place the \label and before the footnote sign. This happens since I updated the macro packages with TeX Live Utility on my Mac at the beginning of November 2024.
As a work around, I enter \kern-0.31em at these places, but that can cause problems at line breaks.
Any better solution is appreciated.

\documentclass{book}
\usepackage{amsthm}
\usepackage{hyperref}
\usepackage{cleveref}
\usepackage{footnotebackref}

\theoremstyle{definition}
\newtheorem{exercise}{Exercise}

\begin{document}
\begin{exercise}[\label{LabelOfExercise}A long
title of this exercise so that the label can't be placed
after it for a good link back to the beginning of
it.\footnote{Make sure you typeset at least twice.}]
Details of this exercise $\ldots$
\end{exercise}
A link back to \cref{LabelOfExercise}.

\end{document}

**Comment by u-fischer** [comment]
Yes, sorry there is a spurious space in firstaid for cleveref, see also https://tex.stackexchange.com/a/730127/2388.

~~~~
\documentclass{book}
\usepackage{amsthm}
\usepackage{hyperref}
\usepackage{cleveref}
\usepackage{footnotebackref}
\RemoveFromHook{label}[firstaid/cleveref]
\makeatletter
\AddToHook{label}[firstaid/cleveref]
         {\ifx
           \@currentcounter\@empty
          \else
           \firstaid@cref@updatelabeldata{\@currentcounter}%<--- was missing
          \fi} 
\makeatother
\theoremstyle{definition}
\newtheorem{exercise}{Exercise}

\begin{document}
\begin{exercise}[\label{LabelOfExercise}A long
title of this exercise so that the label can't be placed
after it for a good link back to the beginning of
it.\footnote{Make sure you typeset at least twice.}]
Details of this exercise $\ldots$
\end{exercise}
A link back to \cref{LabelOfExercise}.

\end{document}
~~~~

**Comment by Uwe-Schmock** [comment]
Thanks a lot, works great!

**Comment by Uwe-Schmock** [comment]
By the end of Nov. 2024, it works again automatically. My thanks to everyone developing and maintaining the hyperref package! I consider the issue as closed.
