### ISSUE TITLE
Load xurl package instead of url package?

### ISSUE THREAD

**Issue by dbitouze** [latex3/hyperref#80]
The package `xurl` loads package `url` by default but, in addition, defines possible URL breaks for all alphanumerical characters and `=` `/` `.` `:` `*` `-` `~` `'` `"`. 

Would be nice for `hyperref` to load it instead of `url` package (OK, it could break existing documents but at least a new option to load the former instead of only the latter would be nice).

**Comment by u-fischer** [comment]
Where is the problem with simply loading xurl yourself if you want the additional breakpoints?

**Comment by dbitouze** [comment]
No problem for me. But it could silently improve the experience of `hyperref`'s users' who often:

- don't know the `url` package and hence don't know `\url` comes from the `url` third party package,
- don't know the `xurl` package and hence don't know it supersedes `url`.

**Comment by davidcarlisle** [comment]
it  is really an option rather than superseding url. I think as a default
the url package choice of just breaking at / is good, I'd only want to
allow breaking at any character (which if course you could also do with the
original url package as well) if the document was particularly tricky with
long url segments being set in a narrow column.
