### ISSUE TITLE
hyperref silently conflicts with \pdfinfo, yielding undefined behavior

### ISSUE THREAD

**Issue by vinc17fr** [latex3/hyperref#99]
When using `\pdfinfo` with hyperref (which may happen in particular when one uses the general `\pdfinfo` command initially and use hyperref later), one gets a PDF file with multiply defined fields. The field that will be taken into account depends on the tool and this creates confusion. If `\pdfinfo` is not supported with hyperref, this command should be redefined to yield an error.

An example:
```
\documentclass{article}
\usepackage{hyperref}
\pdfinfo{/Title (Test)}
\begin{document}
...
\end{document}
```
and the generated PDF file contains: `/Title (Test)/Author()/Title()/Subject()/Creator(LaTeX with hyperref)/Producer(pdfTeX-1.40.20)/Keywords()` i.e. with two `/Title` fields.

**Comment by u-fischer** [comment]
hyperref supports pdfinfo. You can set the /Title e.g. with both syntax:

~~~~
\hypersetup{pdfinfo={Title=Some Info}}
\hypersetup{pdftitle={Some Info}}
~~~~

If you use the primitive command and interfere with the hyperref setup there is not much hyperref can do. Redefining \pdfinfo is a possibility for pdflatex, but this wouldn't disable similar commands for other backends, and it wouldn't work if you use the command before hyperref has been loaded, so it would be only patchwork.

**Comment by vinc17fr** [comment]
At least this would avoid the issue for the main use case. One generally loads packages first and use commands later (except when it is known that a command will have an effect on the package loading), thus this would benefit for most users.

Note that another user got hit by this issue in my old [Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=548825) and [another one via StackExchange](https://tex.stackexchange.com/questions/48067/pdfinfo-doesnt-appear-to-be-working).

**Comment by davidcarlisle** [comment]
I'm inclined to agree with @u-fischer here, pdftex gives no access to any tokens that have been previously passed to `\pdfinfo` so hyperref can not detect this. I don't really see that people generally use packages before commands (other than the obvious cases where the package defines that command) . This case is perhaps most likely to come up as a document class file does `\pdfinfo` and then a user loads hyperref, so use of the command first is as likely as not.

Also as far as possible we try to make the different back ends have the same behaviour and catching this for systems using `\special{..}` would be much harder,

As far as I can see it isn't a PDF error to have two /Title although it is a bit unfortunate that the behaviour is implementation defined.

**Comment by josephwright** [comment]
We could solve this at the format end: move `\pdfinfo` to a new name, provide a wrapper? Seems a bit over-the-top here, and for `expl3` we will be sorting this anyway.

**Comment by u-fischer** [comment]
@davidcarlisle  well actually catching the behaviour for other backends is easier, as they catch it themselves. E.g. this here gives three titles with pdflatex + lualatex but only one (ccc) for dvips + xelatex. For other resources it is often similar, but not always. 

~~~~

\documentclass{article}
\usepackage{l3pdf}
\ExplSyntaxOn
\pdf_uncompress:
\ExplSyntaxOff

\begin{document}
bklblblb
\ExplSyntaxOn
\__pdf_backend_info_gput:nn {Title}{(aaa)}
\__pdf_backend_info_gput:nn {Title}{(bbb)}
\__pdf_backend_info_gput:nn {Title}{(ccc)}
\ExplSyntaxOff
\end{document}
~~~~

@josephwright The problem is that in luatex it is `\pdfextension info` and I don't see how to disable this. And if one gets such clashes with the other backends we can't disable \special.  There will imho stay a number of cases of "Please, simply don't do it".

**Comment by davidcarlisle** [comment]
@josephwright  if we wanted to disable \pdfinfo and enforce all access goes via hyperref then it would b simpler, but I don't think we can do that starting from here, we have to let existing documents that use \pdfinfo and not hyperref work, we could try to redefine \pdfinfo to leave a record that it had been called so hyperref could detect double use, but it seems very fragile and still only for one back end

**Comment by u-fischer** [comment]
@davidcarlisle  Simply recoding that \pdfinfo has been used is not enough. An additional `\pdfinfo{/Blub (zzz)}` is not a problem, the problem is that `\pdfinfo` is called twice with the /Title key. So one would have to retrieve the keys at every call, store and compare them to avoid the double entry.

**Comment by davidcarlisle** [comment]
I think I'll close here, interaction with direct use of the primitives is largely undefined and this whole area is likely to get looked at again with the expl3 backend code
